### ISSUE TITLE
Derived-copy publishing error

### ISSUE THREAD

**Issue by Bkblodget** [Connexions/cnx-press#135] opened 2018-07-28 17:55 UTC
Press seems to throw back a validation error because of the "derived-from" language in the mark-up. 

`Britneys-MacBook-Pro:nebuchadnezzar BritneyBlodget$ neb publish staging col12122 "derived copy test"
col12122/m63579/index.cnxml:86:21 -- error: unfinished element
col12122/m63580/index.cnxml:86:21 -- error: unfinished element
col12122/m63581/index.cnxml:86:21 -- error: unfinished element
col12122/m63582/index.cnxml:86:21 -- error: unfinished element
col12122/m63584/index.cnxml:86:21 -- error: unfinished element
col12122/m63593/index.cnxml:86:21 -- error: unfinished element
col12122/m63594/index.cnxml:86:21 -- error: unfinished element
col12122/m63595/index.cnxml:86:21 -- error: unfinished element
col12122/m63596/index.cnxml:86:21 -- error: unfinished element
col12122/m63597/index.cnxml:86:21 -- error: unfinished element
col12122/m63599/index.cnxml:86:21 -- error: unfinished element
col12122/m63600/index.cnxml:86:21 -- error: unfinished element
col12122/m63601/index.cnxml:86:21 -- error: unfinished element
col12122/m63602/index.cnxml:86:21 -- error: unfinished element
col12122/m63603/index.cnxml:86:21 -- error: unfinished element
col12122/m63604/index.cnxml:86:21 -- error: unfinished element
col12122/m63605/index.cnxml:86:21 -- error: unfinished element
col12122/m63610/index.cnxml:86:21 -- error: unfinished element
col12122/m63611/index.cnxml:86:21 -- error: unfinished element
col12122/m63677/index.cnxml:86:21 -- error: unfinished element
col12122/m63679/index.cnxml:86:21 -- error: unfinished element
col12122/m63680/index.cnxml:86:21 -- error: unfinished element
col12122/m63682/index.cnxml:86:21 -- error: unfinished element
col12122/m63683/index.cnxml:86:21 -- error: unfinished element
col12122/m63684/index.cnxml:86:21 -- error: unfinished element
col12122/m63685/index.cnxml:86:21 -- error: unfinished element
col12122/m63688/index.cnxml:86:21 -- error: unfinished element
col12122/m63689/index.cnxml:86:21 -- error: unfinished element
col12122/m63690/index.cnxml:86:21 -- error: unfinished element
col12122/m63691/index.cnxml:86:21 -- error: unfinished element
col12122/m63693/index.cnxml:86:21 -- error: unfinished element
col12122/m63695/index.cnxml:86:21 -- error: unfinished element
col12122/m63696/index.cnxml:86:21 -- error: unfinished element
col12122/m63697/index.cnxml:86:21 -- error: unfinished element
col12122/m63698/index.cnxml:86:21 -- error: unfinished element
col12122/m63699/index.cnxml:86:21 -- error: unfinished element
col12122/m63700/index.cnxml:86:21 -- error: unfinished element
col12122/m63710/index.cnxml:86:21 -- error: unfinished element
col12122/m63711/index.cnxml:86:21 -- error: unfinished element
col12122/m63712/index.cnxml:86:21 -- error: unfinished element
col12122/m63713/index.cnxml:86:21 -- error: unfinished element
col12122/m63714/index.cnxml:86:21 -- error: unfinished element
col12122/m63716/index.cnxml:75:21 -- error: unfinished element
col12122/m63717/index.cnxml:86:21 -- error: unfinished element
col12122/m63719/index.cnxml:86:21 -- error: unfinished element
col12122/m63724/index.cnxml:86:21 -- error: unfinished element
col12122/m63726/index.cnxml:86:21 -- error: unfinished element
col12122/m63727/index.cnxml:86:21 -- error: unfinished element
col12122/m63733/index.cnxml:86:21 -- error: unfinished element
col12122/m63734/index.cnxml:86:21 -- error: unfinished element
col12122/m63797/index.cnxml:86:21 -- error: unfinished element
col12122/m63798/index.cnxml:86:21 -- error: unfinished element
col12122/m63802/index.cnxml:86:21 -- error: unfinished element
col12122/m63803/index.cnxml:86:21 -- error: unfinished element
col12122/m63804/index.cnxml:86:21 -- error: unfinished element
col12122/m63805/index.cnxml:86:21 -- error: unfinished element
col12122/m63807/index.cnxml:86:21 -- error: unfinished element
col12122/m63808/index.cnxml:86:21 -- error: unfinished element
col12122/m63809/index.cnxml:86:21 -- error: unfinished element
col12122/m63810/index.cnxml:86:21 -- error: unfinished element
col12122/m63811/index.cnxml:86:21 -- error: unfinished element
col12122/m63812/index.cnxml:86:21 -- error: unfinished element
col12122/m63822/index.cnxml:86:21 -- error: unfinished element
col12122/m63823/index.cnxml:86:21 -- error: unfinished element
col12122/m63824/index.cnxml:86:21 -- error: unfinished element
col12122/m63825/index.cnxml:86:21 -- error: unfinished element
col12122/m63826/index.cnxml:86:21 -- error: unfinished element
col12122/m63827/index.cnxml:86:21 -- error: unfinished element
col12122/m63829/index.cnxml:86:21 -- error: unfinished element
col12122/m63831/index.cnxml:86:21 -- error: unfinished element
col12122/m63833/index.cnxml:86:21 -- error: unfinished element
col12122/m63834/index.cnxml:86:21 -- error: unfinished element
col12122/m63835/index.cnxml:86:21 -- error: unfinished element
col12122/m63836/index.cnxml:86:21 -- error: unfinished element
col12122/m63837/index.cnxml:86:21 -- error: unfinished element
col12122/m63849/index.cnxml:86:21 -- error: unfinished element
col12122/m63850/index.cnxml:86:21 -- error: unfinished element
col12122/m63851/index.cnxml:86:21 -- error: unfinished element
col12122/m63852/index.cnxml:86:21 -- error: unfinished element
col12122/m63853/index.cnxml:86:21 -- error: unfinished element
col12122/m63855/index.cnxml:86:21 -- error: unfinished element
col12122/m63856/index.cnxml:86:21 -- error: unfinished element
col12122/m63857/index.cnxml:86:21 -- error: unfinished element
col12122/m63860/index.cnxml:86:21 -- error: unfinished element
col12122/m63861/index.cnxml:86:21 -- error: unfinished element
col12122/m63862/index.cnxml:86:21 -- error: unfinished element
col12122/m63863/index.cnxml:86:21 -- error: unfinished element
col12122/m63886/index.cnxml:86:21 -- error: unfinished element
col12122/m63887/index.cnxml:86:21 -- error: unfinished element
col12122/m63888/index.cnxml:86:21 -- error: unfinished element
col12122/m63889/index.cnxml:86:21 -- error: unfinished element
col12122/m63891/index.cnxml:86:21 -- error: unfinished element
col12122/m63892/index.cnxml:86:21 -- error: unfinished element
col12122/m63893/index.cnxml:86:21 -- error: unfinished element
col12122/m63894/index.cnxml:86:21 -- error: unfinished element
col12122/m63895/index.cnxml:86:21 -- error: unfinished element
col12122/m63896/index.cnxml:86:21 -- error: unfinished element
col12122/m63897/index.cnxml:75:21 -- error: unfinished element
col12122/m63898/index.cnxml:86:21 -- error: unfinished element
col12122/m63901/index.cnxml:86:21 -- error: unfinished element
col12122/m63902/index.cnxml:86:21 -- error: unfinished element
col12122/m63903/index.cnxml:86:21 -- error: unfinished element
col12122/m63904/index.cnxml:86:21 -- error: unfinished element
col12122/m63906/index.cnxml:86:21 -- error: unfinished element
col12122/m63907/index.cnxml:86:21 -- error: unfinished element
col12122/m63908/index.cnxml:86:21 -- error: unfinished element
col12122/m63909/index.cnxml:86:21 -- error: unfinished element
col12122/m63910/index.cnxml:86:21 -- error: unfinished element
col12122/m63911/index.cnxml:86:21 -- error: unfinished element
col12122/m63913/index.cnxml:86:21 -- error: unfinished element
col12122/m63915/index.cnxml:86:21 -- error: unfinished element
col12122/m63916/index.cnxml:86:21 -- error: unfinished element
col12122/m63917/index.cnxml:86:21 -- error: unfinished element
col12122/m63925/index.cnxml:86:21 -- error: unfinished element
col12122/m63929/index.cnxml:86:21 -- error: unfinished element
col12122/m63935/index.cnxml:86:21 -- error: unfinished element
col12122/m63937/index.cnxml:86:21 -- error: unfinished element
col12122/m63938/index.cnxml:86:21 -- error: unfinished element
col12122/m63939/index.cnxml:86:21 -- error: unfinished element
col12122/m63941/index.cnxml:86:21 -- error: unfinished element
col12122/m63942/index.cnxml:86:21 -- error: unfinished element
col12122/m63943/index.cnxml:86:21 -- error: unfinished element
col12122/m63944/index.cnxml:86:21 -- error: unfinished element
col12122/m63945/index.cnxml:86:21 -- error: unfinished element
col12122/m63969/index.cnxml:86:21 -- error: unfinished element
col12122/m63970/index.cnxml:86:21 -- error: unfinished element
col12122/m63971/index.cnxml:86:21 -- error: unfinished element
col12122/m63972/index.cnxml:86:21 -- error: unfinished element
col12122/m63973/index.cnxml:86:21 -- error: unfinished element
col12122/m63974/index.cnxml:86:21 -- error: unfinished element
col12122/m63975/index.cnxml:86:21 -- error: unfinished element
col12122/m63976/index.cnxml:86:21 -- error: unfinished element
col12122/m63990/index.cnxml:86:21 -- error: unfinished element
col12122/m63992/index.cnxml:86:21 -- error: unfinished element
col12122/m63993/index.cnxml:86:21 -- error: unfinished element
col12122/m64021/index.cnxml:86:21 -- error: unfinished element
col12122/m64022/index.cnxml:86:21 -- error: unfinished element
col12122/m64090/index.cnxml:86:21 -- error: unfinished element
col12122/m64092/index.cnxml:86:21 -- error: unfinished element
col12122/m64096/index.cnxml:86:21 -- error: unfinished element
col12122/m64098/index.cnxml:86:21 -- error: unfinished element
col12122/m64100/index.cnxml:86:21 -- error: unfinished element
col12122/m64102/index.cnxml:86:21 -- error: unfinished element
col12122/m64104/index.cnxml:86:21 -- error: unfinished element
col12122/m64108/index.cnxml:86:21 -- error: unfinished element
col12122/m64111/index.cnxml:86:21 -- error: unfinished element
col12122/m64112/index.cnxml:86:21 -- error: unfinished element
col12122/m64113/index.cnxml:86:21 -- error: unfinished element
col12122/m64114/index.cnxml:86:21 -- error: unfinished element
col12122/m64118/index.cnxml:86:21 -- error: unfinished element
col12122/m64121/index.cnxml:86:21 -- error: unfinished element
col12122/m64124/index.cnxml:86:21 -- error: unfinished element
col12122/m64126/index.cnxml:86:21 -- error: unfinished element
col12122/m64130/index.cnxml:86:21 -- error: unfinished element
col12122/m64133/index.cnxml:86:21 -- error: unfinished element
col12122/m64135/index.cnxml:86:21 -- error: unfinished element
col12122/m64137/index.cnxml:86:21 -- error: unfinished element
col12122/m64138/index.cnxml:86:21 -- error: unfinished element
col12122/m64139/index.cnxml:86:21 -- error: unfinished element
col12122/m64146/index.cnxml:86:21 -- error: unfinished element
col12122/m64147/index.cnxml:86:21 -- error: unfinished element
col12122/m64150/index.cnxml:86:21 -- error: unfinished element
col12122/m64152/index.cnxml:86:21 -- error: unfinished element
col12122/m64154/index.cnxml:86:21 -- error: unfinished element
col12122/m64155/index.cnxml:86:21 -- error: unfinished element
col12122/m64156/index.cnxml:86:21 -- error: unfinished element
col12122/m64157/index.cnxml:86:21 -- error: unfinished element
col12122/m64158/index.cnxml:86:21 -- error: unfinished element
col12122/m64159/index.cnxml:86:21 -- error: unfinished element
col12122/m64190/index.cnxml:86:21 -- error: unfinished element
col12122/m64192/index.cnxml:86:21 -- error: unfinished element
col12122/m64196/index.cnxml:86:21 -- error: unfinished element
col12122/m64198/index.cnxml:86:21 -- error: unfinished element
col12122/m64200/index.cnxml:86:21 -- error: unfinished element
col12122/m64270/index.cnxml:86:21 -- error: unfinished element
We've got problems... :(`

**Comment by kerwinso** [comment] 2018-07-30 14:43
@pumazi Here's the markup: https://legacy-staging.cnx.org/content/m63579/latest/source

And here's lines 80-92:

```
</caption>
</figure>
<note id="fs-idp55190864" class="economics bringhome">
<title>Decisions ... Decisions in the Social Media Age</title>
<para xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" id="fs-idm49900128">
To post or not to post? Every day we are faced with a myriad of decisions, from what to have for breakfast, to which route to take to class, to the more complex—“Should I double major and add possibly another semester of study to my education?” Our response to these choices depends on the information we have available at any given moment. Economists call this “imperfect” because we rarely have all the data we need to make perfect decisions. Despite the lack of perfect information, we still make hundreds of decisions a day.
</para>
<para xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" id="fs-idp9173408">
Now we have another avenue in which to gather information—social media. Outlets like Facebook and Twitter are altering the process by which we make choices, how we spend our time, which movies we see, which products we buy, and more. How many of you chose a university without checking out its Facebook page or Twitter stream first for information and feedback?
</para>
<para xmlns:data="http://www.w3.org/TR/html5/dom.html#custom-data-attribute" id="fs-idp26732128">
As you will see in this course, what happens in economics is affected by how well and how fast information disseminates through a society, such as how quickly information travels through Facebook. “Economists love nothing better than when deep and liquid markets operate under conditions of perfect information,” says Jessica Irvine, National Economics Editor for News Corp Australia.
</para>
```

**Comment by Bkblodget** [comment] 2018-07-30 15:34
in atom this is a derived-from validation error:

<img width="659" alt="screen shot 2018-07-30 at 10 34 11 am" src="https://user-images.githubusercontent.com/11299035/43407352-22d4b104-93e4-11e8-8f39-1a4abd30771d.png">

**Comment by pumazi** [comment] 2018-07-30 16:01
during scrum @reedstrm volunteered to look into this

**Comment by Bkblodget** [comment] 2018-07-30 16:02
@reedstrm here is a link to the content on staging: https://staging.cnx.org/contents/bc498e1f-efe9-43a0-8dea-d3569ad09a82@4.48

col12122

**Comment by pumazi** [comment] 2018-07-30 16:03
Was this a module that you previously published with press? I'm wondering if the `derived-from` tag replacement code sloppily removed the tag. One way to verify that is to look at the end of the metadata for a new `derived-from` tag.

**Comment by pumazi** [comment] 2018-07-30 16:16
What version of col12122 is this? This info is now needed because neb requires a version.

**Comment by Bkblodget** [comment] 2018-07-30 21:04
@pumazi I was working on version 1.4 of col12122 and attempting to publish version 1.5. 

To my knowledge, because this collection involved derived modules, it had never been published with press before.

**Comment by pumazi** [comment] 2018-07-31 15:39
Can you paste the results of `pip3 freeze | grep cnxml`?

**Comment by pumazi** [comment] 2018-07-31 15:41
I can verify this via the following steps:
1. `neb get staging col12122 1.4`
2 `neb validate col12122/`

**Comment by pumazi** [comment] 2018-07-31 15:44
This is related to #126 (and therefore https://trello.com/c/DTVFbGtG/).

**Comment by pumazi** [comment] 2018-07-31 16:15
I've been able to reproduce the issue in both linux and osx.

**Comment by pumazi** [comment] 2018-07-31 20:28
According to Slack chat, @reedstrm is working on this... (status update?). My understanding is that he's correcting this issue in the CNXML document generation code within the legacy software.

**Comment by Bkblodget** [comment] 2018-08-02 15:47
This card is dependent on:
https://github.com/Connexions/cnx-press/issues/147
https://github.com/Connexions/cnx-press/issues/126

**Comment by reedstrm** [comment] 2018-09-05 18:05
I believe that all cases on this issue have been addressed. Closing.

**Closed by reedstrm** 2018-09-05 18:05 UTC
Labels: bug
